import React, { useState, useEffect } from 'react';
import {
  FolderKanban,
  X,
  Trash2,
  Download,
  Copy,
  Check,
  FileText,
  Sparkles,
  Plus,
  BookOpen,
  CheckCircle2,
  Compass,
  FileCheck
} from 'lucide-react';
import {
  getBinderItems,
  removeBinderItem,
  clearBinder,
  addBinderItem,
  type BinderItem
} from '../services/binderService';

export interface ResearchBinderDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  onSendToStudio?: (text: string) => void;
}

export const ResearchBinderDrawer: React.FC<ResearchBinderDrawerProps> = ({
  isOpen,
  onClose,
  onSendToStudio
}) => {
  const [items, setItems] = useState<BinderItem[]>(() => getBinderItems());
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [quickNote, setQuickNote] = useState('');
  const [isAddingNote, setIsAddingNote] = useState(false);

  useEffect(() => {
    const handleUpdate = () => setItems(getBinderItems());
    window.addEventListener('scholarforge_binder_updated', handleUpdate);
    return () => window.removeEventListener('scholarforge_binder_updated', handleUpdate);
  }, []);

  const handleCopy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2500);
  };

  const handleAddNote = () => {
    if (!quickNote.trim()) return;
    addBinderItem({
      type: 'note',
      title: 'Scholar Note',
      snippet: quickNote.trim(),
      sourcePillar: 'Manual Entry'
    });
    setQuickNote('');
    setIsAddingNote(false);
  };

  const handleSynthesizeBrief = () => {
    const papers = items.filter((i) => i.type === 'paper');
    const claims = items.filter((i) => i.type === 'claim');
    const stats = items.filter((i) => i.type === 'stat');
    const journals = items.filter((i) => i.type === 'journal');
    const notes = items.filter((i) => i.type === 'note');

    const brief = `# Executive Research Brief & Methodological Dossier
**Generated by**: ScholarForge Suite (Universal Research Binder)
**Date**: ${new Date().toLocaleDateString()}
**Compiled Items**: ${items.length} Clipped Elements

---

## 1. Problem Framing & Core Empirical Claims
${claims.length > 0 ? claims.map((c, i) => `### Claim ${i + 1}: ${c.title}\n> ${c.snippet}\n*Source: ${c.sourcePillar}*`).join('\n\n') : '*No empirical claims clipped yet.*'}

---

## 2. Supporting Literature & Grounded Evidence
${papers.length > 0 ? papers.map((p, i) => `### [${i + 1}] ${p.title}\n${p.snippet}\n*DOI/Metadata: ${p.metadata?.doi || 'Available in bibliography'}*`).join('\n\n') : '*No papers clipped yet.*'}

---

## 3. Methodological Framework & Statistical Parameters
${stats.length > 0 ? stats.map((s, i) => `### Specification ${i + 1}: ${s.title}\n${s.snippet}`).join('\n\n') : '*No statistical specifications clipped yet.*'}

---

## 4. Target Publication Outlets & Strategic Fit
${journals.length > 0 ? journals.map((j, i) => `### Outlet ${i + 1}: ${j.title}\n${j.snippet}\n*Metrics: CiteScore ${j.metadata?.citeScore || 'N/A'}, APC: ${j.metadata?.apc || 'N/A'}*`).join('\n\n') : '*No journals clipped yet.*'}

---

## 5. Working Notes & Qualitative Annotations
${notes.length > 0 ? notes.map((n) => `- **${n.title}** (${n.timestamp}): ${n.snippet}`).join('\n') : '*No working notes recorded.*'}
`;

    return brief;
  };

  const synthesizedBrief = handleSynthesizeBrief();

  const handleDownloadMarkdown = () => {
    const blob = new Blob([synthesizedBrief], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ScholarForge_Research_Brief_${new Date().toISOString().slice(0, 10)}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-hidden bg-slate-900/60 dark:bg-black/80 backdrop-blur-sm animate-in fade-in duration-150">
      
      <div 
        className="fixed inset-y-0 right-0 w-full max-w-lg bg-white dark:bg-slate-900 shadow-2xl border-l border-slate-200 dark:border-slate-800 flex flex-col z-50 animate-in slide-in-from-right duration-200"
      >
        
        {/* Drawer Header */}
        <div className="p-5 border-b border-slate-100 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-950/70 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-blue-900 text-white flex items-center justify-center shadow-xs">
              <FolderKanban className="w-5 h-5 text-amber-300" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold font-serif text-slate-900 dark:text-white">
                  Universal Research Binder
                </h3>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-blue-100 dark:bg-blue-950 text-blue-800 dark:text-blue-300">
                  {items.length} items
                </span>
              </div>
              <p className="text-[11px] text-slate-500">
                Persistent cross-tab scratchpad and executive brief synthesizer.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-slate-200/80 hover:bg-slate-300 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-600 dark:text-slate-300 transition cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Quick Actions Bar */}
        <div className="p-3 border-b border-slate-100 dark:border-slate-800 bg-slate-50/40 dark:bg-slate-950/40 flex items-center justify-between gap-2 text-xs">
          <button
            onClick={() => setIsAddingNote(!isAddingNote)}
            className="px-2.5 py-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-300 dark:border-slate-700 hover:border-blue-500 text-slate-700 dark:text-slate-300 font-bold flex items-center gap-1.5 cursor-pointer shadow-xs"
          >
            <Plus className="w-3.5 h-3.5 text-blue-600" />
            <span>Add Note</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadMarkdown}
              disabled={items.length === 0}
              className="px-2.5 py-1.5 rounded-lg bg-blue-50 hover:bg-blue-100 dark:bg-blue-950 dark:hover:bg-blue-900 text-blue-900 dark:text-blue-300 font-bold flex items-center gap-1.5 cursor-pointer disabled:opacity-40"
              title="Download compiled research brief as Markdown"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export Brief</span>
            </button>

            {items.length > 0 && (
              <button
                onClick={clearBinder}
                className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:hover:bg-rose-950/40 transition cursor-pointer"
                title="Clear all binder items"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>

        {/* Add Note Input Area */}
        {isAddingNote && (
          <div className="p-4 bg-blue-50/50 dark:bg-blue-950/20 border-b border-blue-200 dark:border-blue-900/60 space-y-2 text-xs">
            <textarea
              rows={2}
              value={quickNote}
              onChange={(e) => setQuickNote(e.target.value)}
              placeholder="Jot down a quick methodological note, hypothesis, or idea..."
              className="w-full p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-700 text-xs focus:outline-none focus:border-blue-600"
            />
            <div className="flex justify-end gap-2">
              <button
                onClick={() => setIsAddingNote(false)}
                className="px-3 py-1 rounded-lg text-slate-500 font-bold"
              >
                Cancel
              </button>
              <button
                onClick={handleAddNote}
                className="px-3 py-1 rounded-lg bg-blue-600 text-white font-bold"
              >
                Save to Binder
              </button>
            </div>
          </div>
        )}

        {/* Items List */}
        <div className="flex-1 overflow-y-auto p-4 space-y-3">
          {items.length === 0 ? (
            <div className="p-12 text-center text-xs text-slate-500 space-y-2">
              <FolderKanban className="w-10 h-10 text-slate-300 dark:text-slate-700 mx-auto" />
              <p className="font-semibold text-slate-700 dark:text-slate-300">Your Research Binder is Empty</p>
              <p className="text-[11px] text-slate-400">
                Clip items across Literature Search, Claims Workbench, Synthetic Data, or Journal Sentinel to assemble your unified research brief.
              </p>
            </div>
          ) : (
            items.map((item) => (
              <div
                key={item.id}
                className="p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-2 relative group hover:border-blue-300 dark:hover:border-blue-700 transition"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2">
                    <span className="p-1 rounded-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                      {item.type === 'paper' && <BookOpen className="w-3.5 h-3.5 text-blue-600" />}
                      {item.type === 'claim' && <CheckCircle2 className="w-3.5 h-3.5 text-teal-600" />}
                      {item.type === 'stat' && <Compass className="w-3.5 h-3.5 text-rose-600" />}
                      {item.type === 'journal' && <FileCheck className="w-3.5 h-3.5 text-emerald-600" />}
                      {item.type === 'note' && <FileText className="w-3.5 h-3.5 text-purple-600" />}
                    </span>
                    <span className="font-bold text-slate-900 dark:text-white text-xs truncate max-w-[280px]">
                      {item.title}
                    </span>
                  </div>

                  <button
                    onClick={() => removeBinderItem(item.id)}
                    className="opacity-0 group-hover:opacity-100 p-1 text-slate-400 hover:text-rose-600 transition cursor-pointer"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>

                <p className="text-xs text-slate-600 dark:text-slate-400 line-clamp-3 leading-relaxed">
                  {item.snippet}
                </p>

                <div className="pt-2 border-t border-slate-200/60 dark:border-slate-800/60 flex items-center justify-between text-[10px] text-slate-400 font-mono">
                  <span>{item.sourcePillar}</span>
                  <span>{item.timestamp}</span>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Footer Actions */}
        {items.length > 0 && (
          <div className="p-4 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 space-y-2">
            <div className="flex items-center justify-between gap-2">
              <button
                onClick={() => handleCopy(synthesizedBrief, 'copy-brief')}
                className="flex-1 py-2.5 rounded-xl bg-slate-200 hover:bg-slate-300 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-bold text-xs flex items-center justify-center gap-1.5 cursor-pointer transition"
              >
                {copiedKey === 'copy-brief' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedKey === 'copy-brief' ? 'Copied Brief!' : 'Copy Whole Brief'}</span>
              </button>

              {onSendToStudio && (
                <button
                  onClick={() => {
                    onSendToStudio(synthesizedBrief);
                    onClose();
                  }}
                  className="flex-1 py-2.5 rounded-xl bg-blue-900 hover:bg-blue-800 text-white font-bold text-xs flex items-center justify-center gap-1.5 cursor-pointer transition shadow-xs"
                >
                  <Sparkles className="w-3.5 h-3.5 text-amber-300" />
                  <span>Send to Studio</span>
                </button>
              )}
            </div>
          </div>
        )}

      </div>
    </div>
  );
};
